language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -q build-essential
  - sudo apt-get install -q gfortran
  - sudo apt-get install -q libgsl0-dev
  - sudo apt-get install -q openmpi-bin openmpi-dev
  - sudo apt-get install -q libcppunit-dev
script:
  - ./bootstrap
  - mkdir build && cd build
  - ../configure CC="mpicc" CXX="mpicxx" --enable-coverage
  - make -j4
  - make lcov-reset
  - make check -j4
  - make lcov-report
  - make -j4 distcheck
after_success:
    - bash <(curl -s https://codecov.io/bash)
